### PR TITLE
Support for .Net Standard20

### PR DESCRIPTION
**Pull request by benskid**
Updated all projects other than the unit test project to .Net Standard 2.0. Note this breaks compatibility with .Net Framework <4.7.

Updated the unit test project to .Net Framework 4.7.1 since UT cannot be done from a netstandard project. All UT is passing. 

Had to remove two methods form EmitHelper, please review. Work left: Update version number and release nuget package. Can you help with this?

### CODE REVIEW

**Comment by buunguyen** [comment]
@benskid thanks for this. Would you mind I add you as a collaborator on NuGet so that you can build and publish an update version?

**Comment by buunguyen** [comment]
The changes LGTM btw.

**Comment by benskid** [comment]
> @benskid thanks for this. Would you mind I add you as a collaborator on NuGet so that you can build and publish an update version?

Sure, that'd be fine.

**Comment by buunguyen** [comment]
Thanks, what is your nuget email?

**Comment by benskid** [comment]
bernarddijk@gmail.com

**Comment by buunguyen** [comment]
Is your NuGet username benskid? 
After you build the package and before publishing, would appreciate if you send the PR with all the changes so that the repo is sync'ed.

Please bump up the major version since this is a breaking change. 

Thanks again for working on this.

**Comment by benskid** [comment]
My Nuget username is bernarddijk. Changes are in the commit above.

**Comment by buunguyen** [comment]
Thanks. I've just added your account to Nuget.

**Comment by buunguyen** [comment]
Also added you as collaborator of this repository.

**Comment by benskid** [comment]
> I've just added your account to Nuget.

Not that I can tell; I tried uploading the updated package but was unable. Can you double check?

**Comment by buunguyen** [comment]
I think you have to accept the invitation. There should be an email sent to the address associated with your Nuget.

**Pull request merged**
